provider:
  name: petstore
resources:
  pet:
    create:
      path: /pet
      method: POST
    read:
      path: /pet/{petId}
      method: GET
    schema:
      attributes:
        aliases:
          petId: id
